# SPDX-FileCopyrightText: Steven Ward
# SPDX-License-Identifier: OSL-3.0

# pylint: disable=invalid-name

'''
Filter the colors from https://gitlab.freedesktop.org/xorg/xserver/-/raw/master/os/oscolor.c
and print them as a Python dict.
'''

__author__ = 'Steven Ward'
__license__ = 'OSL-3.0'

import datetime as dt
import os.path
import platform
import re
import sys

now = dt.datetime.now(dt.timezone.utc)
brief_description = 'X11 color names and numbers'
generated_by_file_name = os.path.basename(__file__)
generated_datetime = now.isoformat(timespec='seconds')
system_info = platform.platform()

print(fr'''# SPDX-FileCopyrightText: {__author__}
# SPDX-License-Identifier: {__license__}

"""
{brief_description}
"""

# Generated by "{generated_by_file_name}" on {generated_datetime}
# system information: {system_info}
''')

color_pattern = re.compile(r'\s*{\s*'
                           r'(?P<red>\d+)\s*,\s*'
                           r'(?P<green>\d+)\s*,\s*'
                           r'(?P<blue>\d+)\s*,\s*'
                           r'"(?P<name>[^"]+)\"\s*'
                           r'},', re.ASCII)
grey_pattern = re.compile('grey', re.ASCII | re.IGNORECASE)

print("name_to_rgb = {")
for line in sys.stdin:
    line = line.rstrip(os.linesep)
    match = color_pattern.fullmatch(line)
    if match:
        red = match.group('red')
        green = match.group('green')
        blue = match.group('blue')
        name = match.group('name')
        if not grey_pattern.search(name):
            print(f'    \"{name}\" : ({red}, {green}, {blue}),')
print("}")
