#!/bin/sh

# shellcheck disable=SC1090

# {{{ Copied from [Arch] /etc/X11/xinit/xinitrc

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

: <<EOT
twm &
xclock -geometry 50x50-1+1 &
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
exec xterm -geometry 80x66+0+0 -name login
EOT

# }}}

# {{{ My additions

# No bashisms allowed

if command -v xrdb > /dev/null && [ -f "$XDG_CONFIG_HOME"/xorg/Xresources ]
then
    xrdb -I"$XDG_CONFIG_HOME"/xorg -merge "$XDG_CONFIG_HOME"/xorg/Xresources
fi

# {{{ keyboard

if command -v xset > /dev/null
then
    xset r rate 400 40  # autorepeat delay (ms), repeat rate (#/s)
fi

if command -v setxkbmap > /dev/null
then
    # grep 'ctrl:nocaps' /usr/share/X11/xkb/rules/base.lst
    setxkbmap -option ctrl:nocaps
    # difference between "caps:ctrl_modifier" and "ctrl:nocaps" explained here:
    # https://www.reddit.com/r/commandline/comments/4gusjx/comment/d2lvni3/
fi

# Must do xmodmap after setxkbmap

if command -v xmodmap > /dev/null
then
    # Swap Grave Accent and Tilde
    xmodmap -e 'keycode 49 = asciitilde grave'

    # Look for unused KeyCodes
    #xmodmap -pk | grep -P -x '\s*\d+\s*'

    # Map F13 to an unused KeyCode
    xmodmap -e 'keycode 183 = F13'

    # Map F14 to an unused KeyCode
    xmodmap -e 'keycode 184 = F14'
fi

if command -v xcape > /dev/null
then
    # https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#One-click_key_functions
    #killall --quiet xcape
    #xcape -e 'Caps_Lock=Escape'
    #xcape -e 'Shift_L=Escape'
    xcape -e 'Control_L=Escape;Shift_L=F13;Shift_R=F14'
fi

if command -v sxhkd > /dev/null
then
    sxhkd &
fi

if command -v numlockx > /dev/null
then
    numlockx on
fi

# }}}

# {{{ background

BGCOLOR='#004466'
FGCOLOR='#dddddd'

# NOTE: if xcompmgr will be run, use hsetroot
# https://wiki.archlinux.org/title/Xcompmgr#Background_turns_light_gray_briefly_after_logging_in_(e.g._in_Openbox)
if command -v hsetroot > /dev/null
then
    hsetroot -solid "$BGCOLOR"

elif command -v xsetroot > /dev/null
then
    #xsetroot -solid DodgerBlue4
    xsetroot -solid "$BGCOLOR"
fi

#if command -v xcompmgr > /dev/null
#then
#    xcompmgr -c &
#    #(sleep 1 && xcompmgr -c) &
#fi

if command -v stw > /dev/null
then
    # alpha only works when xcompmgr is running
    #stw -x +50 -y +50 -B 20 -f "$FGCOLOR" -A 0 --
    #stw -x +50 -y +50 -B 20 -f "$FGCOLOR" -b '#003355' --
    COLUMNS=220 stw -x +50 -y +50 -B 20 -f "$FGCOLOR" -b "$BGCOLOR" -F "monospace:size=13" -- \
        sh -c 'LINES=12 top -b -c -n 1 -o %CPU -w ; echo ; echo ; free -h ; echo ; echo ; df -h -T -x squashfs -x tmpfs -x devtmpfs -x vboxsf' &
        # -u $USER
fi

# }}}

# {{{ status bar / root window name

if command -v slstatus > /dev/null
then
    slstatus &

elif command -v xsetroot > /dev/null
then
    #xsetroot -name "$(date +'%a %b %d')"
    # https://wiki.archlinux.org/title/Dwm#Statusbar_configuration
    while true
    do
        #xsetroot -name "$(date +'%F %R')"
        xsetroot -name "$(date +'%a %b %d %R %Z')"
        sleep 30s
    done &
fi

# }}}

# {{{ lock X

if command -v xautolock > /dev/null
then
    if command -v xtrlock > /dev/null
    then
        xautolock -time 15 -locker xtrlock &

    elif command -v slock > /dev/null
    then
        xautolock -time 15 -locker slock &
    fi
fi

# }}}

exec dwm

# }}}
